spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/exhibition?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
  thymeleaf:
    prefix: classpath:/static/
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  resources:
    static-locations=classpath:static/,file:static/
  mvc:
    static-path-pattern=/static/**
mybatis:
  config-location: classpath:mybatis.xml
debug: true
mogu:
  picture:
    upload: /www/uploadFile/moli    #定义文件上传的路径,真实地址
    mapping: /usr/image
server:
  port: 9991
baiduTranslate:
  appid: 20200119000376719
  securityKey: fG26yzXkv9JLfHBr0nQa
jwt:
  expire_time: 86400
role:
  user: user
  admin: admin
  superAdmin: superAdmin
  CSD: CSD
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



